language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install .
script:
    - which sftpd
    - cd example
    - nohup sftpd start >> /dev/null 2>&1 &
    - sleep 1
    - kill -9 `cat sftpd.pid`
