language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install .
script:
    - which sftpd
    - cd example
    - nohup sftpd start > output.txt 2>1 &
    - sleep 2
    - kill -9 `cat sftpd.pid`
    - cat output.txt
    - cat sftpd.log

