language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install .
    - pip install nose
script:
    - ps2
    - ps2.py
